# Generated by Django 4.2.1 on 2023-06-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email1', models.EmailField(blank=True, max_length=254, unique=True)),
                ('email2', models.EmailField(blank=True, max_length=254, unique=True)),
                ('email3', models.EmailField(blank=True, max_length=254, unique=True)),
                ('email4', models.EmailField(blank=True, max_length=254, unique=True)),
                ('participant1', models.CharField(max_length=100)),
                ('participant2', models.CharField(blank=True, max_length=100)),
                ('participant3', models.CharField(blank=True, max_length=100)),
                ('participant4', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('university_name', models.CharField(max_length=200)),
                ('title_of_the_paper', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=100)),
                ('whatsapp_number', models.CharField(max_length=100)),
                ('name_of_the_Second_author', models.CharField(max_length=200)),
                ('name_of_the_Third_author', models.CharField(max_length=200)),
                ('name_of_the_fourth_author', models.CharField(max_length=200)),
                ('name_of_the_fifth_author', models.CharField(max_length=200)),
                ('q1', models.IntegerField(default=5)),
                ('q2', models.IntegerField(default=5)),
                ('q3', models.IntegerField(default=5)),
                ('q4', models.IntegerField(default=5)),
                ('q5', models.IntegerField(default=5)),
                ('q6', models.IntegerField(default=5)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
